# Generated by Django 3.2 on 2021-04-27 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210422_0026'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='fooditem',
            managers=[
            ],
        ),
    ]
