# Generated by Django 3.2 on 2021-04-27 18:54

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_fooditem_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='foodcategory',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='fooditem',
            managers=[
                ('food_items', django.db.models.manager.Manager()),
            ],
        ),
    ]
