# Generated by Django 3.2 on 2021-04-27 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210427_1854'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='fooditem',
            managers=[
            ],
        ),
    ]
