# Generated by Django 3.2 on 2021-04-27 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_creditcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='code',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='expireDate',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='number',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_items', models.ManyToManyField(to='main.FoodItem')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('delivery_address', models.CharField(max_length=255)),
                ('cart_items', models.ManyToManyField(to='main.ShoppingCart')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
