# Generated by Django 3.2 on 2021-04-27 23:58

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210427_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='food_item_photos', validators=[utils.validators.validate_size, utils.validators.validate_extension]),
        ),
    ]
