# Generated by Django 3.2 on 2021-05-03 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_fooditem_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodcategory',
            options={'verbose_name': 'Категория продуктов', 'verbose_name_plural': 'Категории продуктов'},
        ),
        migrations.AlterModelOptions(
            name='fooditem',
            options={'ordering': ('item_name', 'price'), 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
