# Generated by Django 3.2 on 2021-04-28 00:16

from django.db import migrations, models
import utils.upload
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('auth_', '0003_auto_20210427_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='', validators=[utils.validators.validate_size, utils.validators.validate_extension], verbose_name=utils.upload.user_avatar_directory_path),
        ),
    ]
